name: Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs: 
  check-build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
       